# Generated by Django 5.1.4 on 2024-12-18 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('numero_conta', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('logotipo_agencia', models.ImageField(blank=True, null=True, upload_to='logotipo_agencia/')),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracoesAppAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_app', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('descricao_app', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('politica_privacidade_app', models.TextField(blank=True, null=True, unique=True)),
                ('termos_condicoes_app', models.TextField(blank=True, null=True, unique=True)),
                ('logotipo_app', models.ImageField(blank=True, null=True, upload_to='logotipo_app_agente/')),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracoesAppCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_app', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('descricao_app', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('politica_privacidade_app', models.TextField(blank=True, null=True, unique=True)),
                ('termos_condicoes_app', models.TextField(blank=True, null=True, unique=True)),
                ('logotipo_app', models.ImageField(blank=True, null=True, upload_to='logotipo_app_cliente/')),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracoesAppOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_app', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('descricao_app', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('politica_privacidade_app', models.TextField(blank=True, null=True, unique=True)),
                ('termos_condicoes_app', models.TextField(blank=True, null=True, unique=True)),
                ('logotipo_app', models.ImageField(blank=True, null=True, upload_to='logotipo_app_oerador/')),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescontoBilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_desconto', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100, null=True)),
                ('nuit', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('slogan', models.CharField(max_length=500, null=True)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logotipo-empresa/')),
                ('sede', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('classificacao_media', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntasFrequentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('resposta', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntasFrequentesAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('resposta', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntasFrequentesOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('resposta', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerminaisNaconais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=100, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefone', models.IntegerField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='agente_images/')),
                ('endereco', models.TextField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=1000, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_agente', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='AgenteMetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagamento', models.CharField(blank=True, max_length=15, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('default', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agente_metodo_pagamento', to='app.agente')),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agente_agencia', to='app.appmetodopagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('nome_familiar', models.CharField(blank=True, max_length=15, null=True)),
                ('contacto_familiar', models.IntegerField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('token', models.CharField(blank=True, max_length=1000, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteMetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagamento', models.CharField(blank=True, max_length=15, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('default', models.BooleanField(default=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_agencia', to='app.appmetodopagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_metodo_pagamento', to='app.cliente')),
            ],
            options={
                'ordering': ['-default'],
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accao', models.CharField(blank=True, max_length=255, null=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now=True)),
                ('hora_cadastro', models.TimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='operdaor_images/')),
                ('endereco', models.TextField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=1000, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='dono',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operador_empresa', to='app.operador'),
        ),
        migrations.CreateModel(
            name='OperadorMetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagamento', models.CharField(blank=True, max_length=15, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('default', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador_agencia', to='app.appmetodopagamento')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador_metodo_pagamento', to='app.operador')),
            ],
        ),
        migrations.CreateModel(
            name='PontoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('endereco', models.CharField(max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_pontovenda', to='app.empresa')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponto_venda_terminal', to='app.terminaisnaconais')),
            ],
            options={
                'unique_together': {('empresa', 'nome', 'endereco')},
            },
        ),
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('hora_saida', models.TimeField()),
                ('hora_chegada', models.TimeField()),
                ('capacidade_assentos', models.IntegerField(default=61)),
                ('activo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rota_agente', to='app.agente')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_rota_destino', to='app.pontovenda')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_rota', to='app.empresa')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_rota_origem', to='app.pontovenda')),
            ],
        ),
        migrations.CreateModel(
            name='PontoIntermediario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(max_length=255)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rota_ponto_intermedio', to='app.rotas')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(null=True)),
                ('data_chegada', models.DateField(null=True)),
                ('hora_saida', models.TimeField(null=True)),
                ('hora_chegada', models.TimeField(null=True)),
                ('total_assento', models.IntegerField(default=61)),
                ('total_assentos_disponiveis', models.IntegerField(default=61)),
                ('contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('data_fecho', models.DateTimeField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('duracao_viagem', models.CharField(blank=True, max_length=20, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agente_viagem', to='app.agente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_viagem', to='app.empresa')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agente_viagem_rota', to='app.rotas')),
            ],
            options={
                'ordering': ['-data_saida'],
            },
        ),
        migrations.CreateModel(
            name='VendaBilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10)),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('hora_venda', models.TimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_bilhete_agente', to='app.agente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venda_bilhete_cliente', to='app.cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_bilhete_emoresa', to='app.empresa')),
                ('metodo_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_bilhete_metodo_pagamento', to='app.clientemetodopagamento')),
                ('viagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_bilhete_viagem', to='app.viagem')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('origem', models.CharField(blank=True, max_length=500, null=True)),
                ('destino', models.CharField(blank=True, max_length=500, null=True)),
                ('motivo', models.CharField(blank=True, max_length=500, null=True)),
                ('assento', models.IntegerField()),
                ('nome_passageiro', models.CharField(max_length=500)),
                ('contacto_passageiro', models.CharField(max_length=500)),
                ('nome_familiar', models.CharField(max_length=500)),
                ('contacto_familiar', models.CharField(max_length=500)),
                ('status_bilhete', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10)),
                ('status_viagem', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Adamento', 'Adamento'), ('Realizada', 'Realizada')], default='Pendente', max_length=10)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duracao', models.CharField(blank=True, max_length=500, null=True)),
                ('contacto_empresa', models.CharField(blank=True, max_length=500, null=True)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='bilhete_qr_code/')),
                ('data_criado', models.DateField(auto_now_add=True)),
                ('hora_criado', models.TimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilhetes_cliente', to='app.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilhetes_empresa', to='app.empresa')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilhete_vendido', to='app.vendabilhete')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilhetes_viagem', to='app.viagem')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ViagemAssento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assento', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=False)),
                ('data_criado', models.DateTimeField(auto_now=True)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_assento', to='app.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_classificacao', models.DateTimeField(auto_now_add=True)),
                ('bilhete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes_bilhete', to='app.bilhete')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes_cliente', to='app.cliente')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes_viagem', to='app.viagem')),
            ],
            options={
                'unique_together': {('viagem', 'cliente')},
            },
        ),
    ]
