# Generated by Django 5.1.4 on 2025-01-02 07:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='agente_images/'),
        ),
        migrations.AlterField(
            model_name='appmetodopagamento',
            name='logotipo_agencia',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logotipo_agencia/'),
        ),
        migrations.AlterField(
            model_name='bilhete',
            name='qrcode',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='bilhete_qr_code/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_images/'),
        ),
        migrations.AlterField(
            model_name='configuracoesappagente',
            name='logotipo_app',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logotipo_app_agente/'),
        ),
        migrations.AlterField(
            model_name='configuracoesappcliente',
            name='logotipo_app',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logotipo_app_cliente/'),
        ),
        migrations.AlterField(
            model_name='configuracoesappoperador',
            name='logotipo_app',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logotipo_app_oerador/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logotipo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logotipo-empresa/'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='operdaor_images/'),
        ),
    ]
