# Generated by Django 5.1.4 on 2024-12-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoesappagente',
            name='descricao_app',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='configuracoesappagente',
            name='politica_privacidade_app',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracoesappagente',
            name='termos_condicoes_app',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracoesappcliente',
            name='descricao_app',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='configuracoesappcliente',
            name='politica_privacidade_app',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracoesappcliente',
            name='termos_condicoes_app',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracoesappoperador',
            name='descricao_app',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='configuracoesappoperador',
            name='politica_privacidade_app',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracoesappoperador',
            name='termos_condicoes_app',
            field=models.TextField(blank=True, null=True),
        ),
    ]
