# Generated by Django 5.1.4 on 2025-01-02 08:05

import cloudinary.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_agente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmetodopagamento',
            name='logotipo_agencia',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2025, 1, 2, 8, 5, 1, 730825, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='logotipo_agencia/'),
            preserve_default=False,
        ),
    ]
