# Generated by Django 5.1.4 on 2025-01-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_appmetodopagamento_logotipo_agencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='agente_images/'),
        ),
        migrations.AlterField(
            model_name='appmetodopagamento',
            name='logotipo_agencia',
            field=models.ImageField(blank=True, null=True, upload_to='logotipo_agencia/'),
        ),
        migrations.AlterField(
            model_name='bilhete',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='bilhete_qr_code/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='configuracoesappagente',
            name='logotipo_app',
            field=models.ImageField(blank=True, null=True, upload_to='logotipo_app_agente/'),
        ),
        migrations.AlterField(
            model_name='configuracoesappcliente',
            name='logotipo_app',
            field=models.ImageField(blank=True, null=True, upload_to='logotipo_app_cliente/'),
        ),
        migrations.AlterField(
            model_name='configuracoesappoperador',
            name='logotipo_app',
            field=models.ImageField(blank=True, null=True, upload_to='logotipo_app_oerador/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='logotipo-empresa/'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='operdaor_images/'),
        ),
    ]
