# Generated by Django 5.1.4 on 2025-01-02 09:15

import cloudinary.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_agente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2025, 1, 2, 9, 14, 50, 275523, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='agente_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appmetodopagamento',
            name='logotipo_agencia',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2025, 1, 2, 9, 15, 3, 118101, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='logotipo_agencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bilhete',
            name='qrcode',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2025, 1, 2, 9, 15, 5, 634145, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='bilhete_qr_code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2025, 1, 2, 9, 15, 7, 765318, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='profile_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracoesappagente',
            name='logotipo_app',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2025, 1, 2, 9, 15, 9, 858454, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='logotipo_app_agente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracoesappcliente',
            name='logotipo_app',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2025, 1, 2, 9, 15, 11, 737075, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='logotipo_app_cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracoesappoperador',
            name='logotipo_app',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2025, 1, 2, 9, 15, 13, 592929, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='logotipo_app_oerador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logotipo',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2025, 1, 2, 9, 15, 15, 451063, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='logotipo-empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operador',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2025, 1, 2, 9, 15, 17, 676618, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='operdaor_images'),
            preserve_default=False,
        ),
    ]
