# Generated by Django 5.1.4 on 2025-01-04 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_agente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendabilhete',
            name='viagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venda_bilhete_viagem', to='app.viagem'),
        ),
        
    ]
