# Generated by Django 5.1.4 on 2025-01-04 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_vendabilhete_viagem'),
    ]

    operations = [
       
    ]
